argument_specs:
  main:
    short_description: Setup the owner server
    description: 
      - Checks RHEL subscription and installs fdo-rendezvous-server package with dnf.
        Creates FDO keys directory, copies manufacturer certificate from manufacturing server and creates rendezvous service keys stores.
        It then copies the rendezvous server config example. starts and enables the FDO rendezvous server service and opens required ports. 
    
    options:
      fdo_src:
        description:
          - Fdo directory path.
        type: str
        default: /etc/fdo
      manufacturing_server_fdo_src:
        description:
          - Fdo directory path on the manufacturing server.
          type: str
          default: /etc/fdo    
