---
- name: Copy Ownership Voucher from Manufacturing Server
  synchronize:
    src: "{{ manufacturing_server_ownership_vouchers_dir }}/"
    dest: "{{ localhost_ownership_vouchers_dir }}"
    mode: pull
