---
- name: Check RHEL Subscription
  command: subscription-manager status
  register: subscriptionStatus
  ignore_errors: true

- name: RHEL Subscription
  fail:
    msg: RHEL Subscription not available.
  when: '"Overall Status: Current" not in subscriptionStatus.stdout'

- name: Install Packages
  ansible.builtin.dnf:
    state: latest
    name:
      - fdo-rendezvous-server

- name: Creates FDO Keys Directory
  file:
    path: /etc/fdo/keys
    state: directory
    mode: 0775

# TODO: configure delegated machine 
- name: Copy Manufacturer Certificate from Manufacturing Server
  synchronize:
    src: /etc/fdo/keys/manufacturer_cert.pem
    dest: /etc/fdo/keys/manufacturer_cert.pem
  delegate_to: '{{target|default("manufacturing_server")}}'

- name: Create Rendezvous Service Keys Stores
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
    recurse: yes
  loop:
    - /etc/fdo/stores/rendezvous_registered
    - /etc/fdo/stores/rendezvous_sessions

# TODO: add option to edit the default config
- name: Copy Rendezvous Server Config
  copy:
    src: /usr/share/doc/fdo/rendezvous-server.yml
    dest: /etc/fdo/rendezvous-server.yml
    remote_src: yes

- name: Start and Enable FDO Rendezvous Server Service
  systemd:
    name: fdo-rendezvous-server
    state: started
    enabled: yes

- name: Open Required Ports
  ansible.posix.firewalld:
    port: 8082/tcp
    permanent: yes
    state: enabled
    immediate: true