image: python:3.8.12-slim-buster  # TODO gitlab registry

# TODO reuse Makefile - "make sanity", and docker dind.

variables:
  MY_VAR: myvalue

stages:
  - test
  - build  # build collection tar.gz
  - deploy  # push collection tar.gz to galaxy

coverage:
  stage: test
  image: python:3.8.12-slim-buster
  before_script:
    - pip3 install -r sanity.requirements -r test.requirements
    - apt update
    - apt install -y git
  script:
    - pip install ansible-core==2.13.3
    # ansible-test needs special directory structure.
    - mkdir -p /work-dir/ansible_collections/community/
    - cp -a ./  /work-dir/ansible_collections/community/fdo
    - pushd /work-dir/ansible_collections/community/fdo
    #
    # - ansible-test coverage erase --venv
    # Use venv, until we agree about dind - eventually we need to move to github anyway?
    - ansible-test units --coverage
    - ansible-test coverage html --requirements
    - ansible-test coverage report --omit 'tests/*' --show-missing
    - ls -al tests/output/reports/coverage
    - popd
    #
    # Move artifacts back to initial dir, so they can be collected by gitlab.
    - mkdir -p tests/output/reports/coverage
    - cp -a /work-dir/ansible_collections/community/fdo/tests/output/reports/coverage/ tests/output/reports/coverage/
    - ls -al tests/output/reports/coverage
  artifacts:
    paths:
      - tests/output/reports/coverage
    expose_as: html_coverage
    expire_in: 10 week

sanity:
  stage: test
  image: python:3.8.12-slim-buster
  before_script:
    - pip3 install -r sanity.requirements -r test.requirements
    - apt update
    - apt install -y git
  script:
    - pip install ansible-core==2.13.3
    # ansible-test needs special directory structure.
    - mkdir -p /work-dir/ansible_collections/community/
    - cp -a ./  /work-dir/ansible_collections/community/fdo
    - pushd /work-dir/ansible_collections/community/fdo
    #
    # Same as "make sanity"
    # TODO reuse Makefile
    - black -t py38 --check --diff --color plugins tests/unit
    - flake8 --exclude tests/output/
    - ansible-test sanity

integration:
  stage: test
  image: python:3.8.12-slim-buster
  before_script:
    - pip3 install -r sanity.requirements -r test.requirements
    - apt update
    - apt install -y git
  script:
    - pip install ansible-core==2.13.3
    # ansible-test needs special directory structure.
    - mkdir -p /work-dir/ansible_collections/community/
    - cp -a ./  /work-dir/ansible_collections/community/fdo
    - pushd /work-dir/ansible_collections/community/fdo
    #
    - |
      cat <<EOF >tests/integration/integration_config.yml
      # Generated by .gitlab-ci.yml
      my_var: ${MY_VAR}
      EOF
    - cat tests/integration/integration_config.yml
    - ansible-test integration
