---
# configuration settings
fdo_src: /etc/fdo
enable_roll_back: true

# rendezvous-server.yml
rendezvous_server_storage_driver_path: "{{ fdo_src }}/stores/rendezvous_registered"
rendezvous_server_session_store_driver_path: "{{ fdo_src }}/stores/rendezvous_sessions"
rendezvous_server_trusted_manufacturer_keys_path: "{{ fdo_src }}/keys/manufacturer_cert.pem"
rendezvous_server_max_wait_seconds: ~
rendezvous_server_bind_ip: 0.0.0.0
rendezvous_server_listen_port_rendezvous_server: 8082
