---
- name: Copy Ownership Voucher from Manufacturing Server
  synchronize:
    src: "{{ manufacturing_server_ownership_vouchers_dir }}/"
    dest: "{{ owner_server_ownership_vouchers_dir }}"
  delegate_to: "{{ manufacturing_server_url }}"
