---
#
# Backup the old config file and create a new ones from template.
#
- name: Copy Old Rendezvous Server Config
  copy:
    src: "{{ fdo_src }}/rendezvous-server.yml"
    dest: "{{ fdo_src }}/rendezvous-server.yml.old"
    remote_src: yes

- name: Configure Rendezvous Server
  template:
    src: ../templates/rendezvous-server.yml.j2
    dest: "{{ fdo_src }}/rendezvous-server.yml"
