---
- name: Copy Ownership Voucher from localhost
  synchronize:
    src: "{{ localhost_ownership_vouchers_dir }}/"
    dest: "{{ owner_server_ownership_vouchers_dir }}"
    checksum: true
    rsync_timeout: 60
