---
- import_role:
    name: check_rhel_subscription

- name: Install Packages
  ansible.builtin.dnf:
    state: latest
    name:
      - fdo-rendezvous-server
      - firewalld
      - sshpass
      - rsync

- name: Creates FDO Keys Directory
  file:
    path: "{{ fdo_src }}/keys"
    state: directory
    mode: 0775

- name: Copy Manufacturer Certificate from Manufacturing Server
  synchronize:
    src: "{{ manufacturing_server_fdo_src }}/keys/manufacturer_cert.pem"
    dest: "{{ fdo_src }}/keys/manufacturer_cert.pem"
  delegate_to: "{{ manufacturing_server_url }}"

- name: Create Rendezvous Service Keys Stores
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
    recurse: yes
  loop:
    - "{{ fdo_src }}/stores/rendezvous_registered"
    - "{{ fdo_src }}/stores/rendezvous_sessions"

- name: Copy Rendezvous Server Config
  copy:
    src: /usr/share/doc/fdo/rendezvous-server.yml
    dest: "{{ fdo_src }}/rendezvous-server.yml"
    remote_src: yes

- name: Start and Enable FDO Rendezvous Server Service
  systemd:
    name: fdo-rendezvous-server
    state: started
    enabled: yes

- name: Start firewalld service 
  service:
    name: firewalld
    state: started

- name: Open Required Ports
  ansible.posix.firewalld:
    port: 8082/tcp
    permanent: yes
    state: enabled
    immediate: true
