---
#
# Updates Manufacturing Server Device/Owner keys/certificates.
#
- name: Copy Device Certificates from Manufacturing Server
  synchronize:
    src: "{{ manufacturing_server_fdo_src }}/keys/device_ca_cert.pem"
    dest: "{{ fdo_src }}/keys/device_ca_cert.pem"
  delegate_to: "{{ manufacturing_server_url }}"

- name: Copy Owner Key from Manufacturing Server
  synchronize:
    src: "{{ manufacturing_server_fdo_src }}/keys/owner_key.der"
    dest: "{{ fdo_src }}/keys/owner_key.der"
  delegate_to: "{{ manufacturing_server_url }}"

- name: Copy Owner Certificate from Manufacturing Server
  synchronize:
    src: "{{ manufacturing_server_fdo_src }}/keys/owner_cert.pem"
    dest: "{{ fdo_src }}/keys/owner_cert.pem"
  delegate_to: "{{ manufacturing_server_url }}"