---
- name: Copy Ownership Voucher from Manufacturing Server
  synchronize:
    src: "{{ manufacturing_server_ownership_vouchers_dir }}/{{ ownership_voucher_uuid }}"
    dest: "{{ owner_server_ownership_vouchers_dir }}/{{ ownership_voucher_uuid }}"
  delegate_to: '{{target|default("manufacturing_server")}}'
