- name: test vm module
  hosts: localhost
  gather_facts: False

  tasks:
    - name: message-1
      community.fdo.sample_module:
        filename: /tmp/message-1

    - name: use osbuild.composer.builder
      osbuild.composer.list_blueprints:
      register: list_blueprints_out
      when: 0
