# TODO - try to use https://github.com/marketplace/actions/ansible-test
name: Perform testing with ansible-test
on: [push]
env:
  WORKDIR: /work-dir/ansible_collections/community/fdo
  MY_VAR: ci_my_var
jobs:
  units:
    runs-on: [self-hosted, linux]
    container: python:3.10-bullseye
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: pip3 install -r sanity.requirements -r test.requirements
      - run: pip install ansible-core==2.13.4
      - run: apt update
      - run: apt install -y git make
        # ansible-test needs special directory structure.
      - run: mkdir -p $WORKDIR
      - run: cp -a ./ $WORKDIR
        #
      - run: cd $WORKDIR && ansible-test units --python 3.10
      - run: cd $WORKDIR && ansible-test coverage html --requirements
      - run: cd $WORKDIR && ansible-test coverage report --omit 'tests/*' --show-missing

  sanity:
    runs-on: [self-hosted, linux]
    container: python:3.10-bullseye
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: pip3 install -r sanity.requirements -r test.requirements
      - run: pip install ansible-core==2.13.4
      - run: apt update
      - run: apt install -y git make
        # ansible-test needs special directory structure.
      - run: mkdir -p $WORKDIR
      - run: cp -a ./ $WORKDIR
        #
      - run: cd $WORKDIR && black -t py38 --check --diff --color plugins tests/unit
      - run: cd $WORKDIR && flake8 --exclude tests/output/
      - run: cd $WORKDIR && ansible-test sanity

  integration:
    runs-on: [self-hosted, linux]
    container: python:3.10-bullseye
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: pip3 install -r sanity.requirements -r test.requirements
      - run: pip install ansible-core==2.13.4
      - run: apt update
      - run: apt install -y git make
        # ansible-test needs special directory structure.
      - run: mkdir -p $WORKDIR
      - run: cp -a ./ $WORKDIR
        #
      - run: |
          cat <<EOF >$WORKDIR/tests/integration/integration_config.yml
          # Generated by .github/workflow/
          my_var: ${MY_VAR}
          my_password: ${{ secrets.my_password }}
          EOF
      - run: cd $WORKDIR && ansible-test integration -v
